server:
 port: 9079

jwt:
  secret: ${AUTH_JWT_SECRET}
  token:
    validity: ${AUTH_JWT_TOKEN_VALIDITY}
  refreshtoken:
    validity: ${AUTH_JWT_REFRESH_TOKEN_VALIDITY}

kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: ${KAFKA_CONSUMER_BOOTSTRAP_SERVERS}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        isolation:
        level: read_committed
        spring:
          json:
            trusted:
              packages: "*"
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: 'false'
      group-id: campaign_auth
    producer:
      bootstrap-servers: ${KAFKA_CONSUMER_BOOTSTRAP_SERVERS}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      email: email_topic
      sms: sms_topic
      user: campaign_user
      inquiry: user_inquiry
      actionCard: actionCard_User
      delete-users: delete_users
